import { Sparkles } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';

interface EstimatedBadgeProps {
  /** Bill-text quote/paraphrase justifying the figure, if any. */
  basis?: string;
  /** AI's stated assumptions. */
  assumptions?: string;
  className?: string;
}

/**
 * Inline badge that flags a $ figure as an AI-generated projection rather than
 * a number lifted from the bill. Hover shows the methodology + any cited basis.
 */
const EstimatedBadge = ({ basis, assumptions, className }: EstimatedBadgeProps) => {
  return (
    <TooltipProvider delayDuration={150}>
      <Tooltip>
        <TooltipTrigger asChild>
          <span
            className={cn(
              'inline-flex items-center gap-1 rounded-full border border-primary/30 bg-primary/10 px-1.5 py-0.5 text-[10px] font-medium text-primary cursor-help',
              className,
            )}
            aria-label="AI-estimated figure"
          >
            <Sparkles className="w-2.5 h-2.5" />
            Est.
          </span>
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-xs">
          <p className="font-semibold mb-1">AI projection</p>
          <p className="text-xs text-muted-foreground mb-2">
            This dollar figure is a 5-year projection generated by AI from Ohio sector
            baselines and the bill text — not a number lifted from the bill itself.
          </p>
          {basis && (
            <div className="mb-2">
              <p className="text-xs font-medium">Cited basis</p>
              <p className="text-xs text-muted-foreground italic">"{basis}"</p>
            </div>
          )}
          {assumptions && (
            <div>
              <p className="text-xs font-medium">Assumptions</p>
              <p className="text-xs text-muted-foreground">{assumptions}</p>
            </div>
          )}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};

export default EstimatedBadge;
